language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
gemfile:
#  - gemfiles/Gemfile.rails-2.0.x
#  - gemfiles/Gemfile.rails-2.1.x
  - gemfiles/Gemfile.rails-2.2.x
  - gemfiles/Gemfile.rails-2.3.x
exclude:
  - rvm: 1.9.2
    gemfile: gemfiles/Gemfile.rails-2.2.x
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile.rails-2.2.x
